name: diseas_discover
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  http: ^1.2.1 
  url_launcher: ^6.1.14 
  firebase_core: ^2.27.0  # Or a slightly newer 2.x.x version
  firebase_auth: ^4.17.8 # Or a slightly newer 4.x.x version
  cloud_firestore: ^4.15.8 # Or a slightly newer 4.x.x version
  intl: ^0.19.0
  google_fonts: ^6.2.1
  

  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #-------------------Local Assets------------------#
     - assets/icons/
     - assets/logos/
     - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # Or whatever your min Sdk is