// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoGzClQIatz5LVmq9rYSZqmzxJT_3SLps',
    appId: '1:1076154535412:web:16975f83d40c92bcc3fda1',
    messagingSenderId: '1076154535412',
    projectId: 'diseas-discover',
    authDomain: 'diseas-discover.firebaseapp.com',
    storageBucket: 'diseas-discover.firebasestorage.app',
    measurementId: 'G-PKR02F8M4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqep8M1PujFLwo9y0BPC7pQ1gYce4u-jo',
    appId: '1:1076154535412:android:419a432e6789746dc3fda1',
    messagingSenderId: '1076154535412',
    projectId: 'diseas-discover',
    storageBucket: 'diseas-discover.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibKlp0r-0LHD1gsTQUW0W5S059EEMeIc',
    appId: '1:1076154535412:ios:7c6e7f0b27103980c3fda1',
    messagingSenderId: '1076154535412',
    projectId: 'diseas-discover',
    storageBucket: 'diseas-discover.firebasestorage.app',
    iosBundleId: 'com.example.diseasDiscover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibKlp0r-0LHD1gsTQUW0W5S059EEMeIc',
    appId: '1:1076154535412:ios:7c6e7f0b27103980c3fda1',
    messagingSenderId: '1076154535412',
    projectId: 'diseas-discover',
    storageBucket: 'diseas-discover.firebasestorage.app',
    iosBundleId: 'com.example.diseasDiscover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoGzClQIatz5LVmq9rYSZqmzxJT_3SLps',
    appId: '1:1076154535412:web:b1f47eb26c7a61d8c3fda1',
    messagingSenderId: '1076154535412',
    projectId: 'diseas-discover',
    authDomain: 'diseas-discover.firebaseapp.com',
    storageBucket: 'diseas-discover.firebasestorage.app',
    measurementId: 'G-57Y145S5VL',
  );

}